config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"

  resources :users_controller, only: [:show]do
  #Permet d'avoir un path qui s'imbrique avec ceux de user
  resources :avatars, only: [:create] 
   end
  resources :events
  resources :charges

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :participations
	has_many :users , through: :participations
	belongs_to :admin , class_name: "User"

		validates :start_date ,
			presence:true,
			if: :isEventNotPast 

		validates :duration , 
			presence:true,
			numericality: {greater_than: 0},
			if: :durationMultipleFive

		validates :title,
			presence:true,
			length:{in: 5..140}	

		validates :description,
			presence:true,
			length:{in: 20..1000}

		validates :price , 
			presence:true,
			numericality: {greater_than: 0,less_than: 1000}	

		validates :location , 
			presence:true


	def isEventNotPast()	
		if(!self.nil?)then
		return start_date > Date.today
		else return false	
		end
	end

	def durationMultipleFive()
		if(self.nil?)then
		return 	duration.modulo(5) == 0
		else return false
		end
	end

	def end_date
		if(self !=nil)
		return start_date + duration*60 
		end
		return 0
	end
end

app/models/participation.rb
class Participation < ApplicationRecord
	belongs_to :user 
	belongs_to :event
	after_create :participation_confirm
	validates_uniqueness_of :event_id, :scope => :user_id

	def participation_confirm
		ParticipationMailer.participation_email(self).deliver_now
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    has_one_attached :avatar
	has_many :participations
	has_many :eventsParticipated , through: :participations , source: :event
	has_many :events ,foreign_key: "admin_id"

	after_create :welcome_send

	def welcome_send
		UserMailer.welcome_email(self).deliver_now
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_devise_parameters, if: :devise_controller?

	def configure_devise_parameters
	  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name,:email, :password, :password_confirmation)}
	  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, 
	  	:last_name,:email, 
	  	:password, :password_confirmation,:current_password,
	  	:description)}
	end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
def create
    @user = User.find(params[:users_controller_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(users_controller_path(@user))
end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create({
	    email: params[:stripeEmail],
	    source: params[:stripeToken],
	  })

	  charge = Stripe::Charge.create({
	    customer: customer.id,
	    amount: @amount,
	    description: 'Rails Stripe customer',
	    currency: 'usd',
	  })

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  end

  def index
  	@events = Event.all
  	
  end

  def show
  	@event = Event.find(params[:id])
  	if(user_signed_in?)then
	  	@isMyevent = isMyevent?(@event.id)
	  	@alreadySuscribed = alreadySuscribed?(@event.id)
  	end
  end

  def create
	  	puts "Controller Event create".colorize(:green)
	  	@state = false
	  	hashdate= params[:event]
		date = Date.new
		if( !hashdate[:start_date].eql?("") )then date = Date.strptime(hashdate[:start_date],'%Y-%m-%d') end

	  	@event=Event.new(start_date:date,
	  		duration:params[:duration],
	  		title:params[:title],
	  		description:params[:description],
	  		price:params[:price],
	  		location:params[:location] ,
	  		admin_id: current_user.id)

		@state = @event.save
		  	if @state then # essaie de sauvegarder en base @gossip
		  		flash[:success] = "Votre event a été publié !"
		    	redirect_to  root_path
		  	else
		  		#Reaffiche la page 
		  		puts @event.errors.full_messages
		  		render :new
		    end
  	end

  	def isMyevent?(id)
  		return current_user.events.ids.include?(id)
  	end

  	def alreadySuscribed?(id)
  		return current_user.eventsParticipated.ids.include?(id)
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def Index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :authenticate_user!, only: [:secret]
	
  def index
  end

  def secret
  end
end

app/controllers/users_controller_controller.rb
class UsersControllerController < ApplicationController
	before_action :authenticate_user , only: [:show,:edit,:update,:destroy]

	def authenticate_user
			unless user_signed_in?
				redirect_to new_user_session_path
			end
	end

	def show
	  	puts "Controller User show"
	  	@user = User.find(params[:id])
	end

	def update
		
	end

	def edit
		
	end

	def destroy
		
	end
  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/charges/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>New strip charge</title>
</head>
<body>
	<%= form_tag charges_path do %>
		  <article>
		    <% if flash[:error].present? %>
		      <div id="error_explanation">
		        <p><%= flash[:error] %></p>
		      </div>
		    <% end %>
		    <label class="amount">
		      <span>Amount: $5.00</span>
		    </label>
		  </article>

		  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
		          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		          data-description="A month's subscription"
		          data-amount="500"
		          data-locale="auto"></script>
		<% end %>

</body>
</html>

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Index events</title>
</head>
<body>
<div class="row">
	<%@events.each{|event|%>
	<div class="col-lg-4 col-sm-6 portfolio-item">
		<div class="card h-100 w-100">
		  	<div class="card-body">
			    <h5 class="card-title "><%=event.title%></h5>
			    <%= link_to "Détails ",event_path(id:event.id),class:"card-link badge badge-secondary"%>
			</div>
		</div>
	</div>
	<%}%>
</dir>

</body>
</html>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Creer evenement</title>
</head>
<body>
	<h1>Creation d'évenement</h1>
<div class="row justify-content-center">
    	<dir>
	    	<%= form_tag events_path(action: 'create'), method: "post" do %>

	      <%= label_tag "Titre" %>
	      <br />
	      <%= text_field_tag 'title', params[:title] %>
	      <br /> <br />

	      <%= label_tag "Date de l'evenement" %>
	      <br />
	      <%=datetime_field("event", "start_date", min: Date.today, default: Date.today)%>	      
	      <br /> <br />

	      <%= label_tag 'Durée' %>
	      <br />
	      <%= number_field_tag 'duration',0 %>
	      <br /> <br />      

	      <%= label_tag 'Description' %>
	      <br />
	      <%= text_area_tag 'description',"Une description",:rows=>5, :cols=>60 %>
	      <br /> <br />

	      <%= label_tag 'Prix' %>
	      <br />
	      <%= number_field_tag 'price',1 %>
	      <br /> <br />

	      <%= label_tag "Lieu" %>
	      <br />
	      <%= text_field_tag 'location', params[:location] %>
	      <br /> <br />

	      <%= submit_tag "Creer event" %>

	    	<% end %>
    	</dir>

    </div>
<% if @state == false  %>
	    <div class="row justify-content-center "style="padding-top: 1cm;">
			<div class="card card text-white bg-danger mb-3" style="width: 30cm;">
			<div class="card-header text-uppercase font-weight-bold">
			Attention erreur de saisis !
			</div>
			<div class="card-body">
			  <p>Nous n'avons pas réussi à creer l'event pour la (ou les) raison(s) suivante(s) :</p>
			  <ul>
			    <% @event.errors.full_messages.each do |message| %>
			      <li><%= message %></li>
			    <% end %>
			  </ul>
			</div>
			</div>
		</div>
	<% end %>

</body>
</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Details de l'event</title>
</head>
<body>
<div class="card border-success mb-0" >
  <div class="card-header bg-transparent border-success text-success">
    <%if(@alreadySuscribed) then%>
    Vous etes déja inscrit !
    <%elsif (!@isMyevent) %>
    <%=link_to "Participer",new_charge_path%>
    <%end%>

    <br><br>
    prix : <%=@event.price%> €</div>
  <div class="card-body ">
    <h2 class="card-title"><%=@event.title%></h2>
    <p class="card-text"><%=@event.description%></p>
  </div>
  <div class="card-footer bg-transparent border-success">
  	
  	<p>Le <%=@event.start_date.strftime('%a %d %b %Y ') %>  à <%=@event.location%> </p>
  	<p>A partir de <%=@event.start_date.strftime('%Hh%M') %> jusqu'à <%=@event.end_date.strftime('%Hh%M') %>  </p>
  	<p>Nombre de participants : <%=@event.users.size%></p>
  	<p> Contact :  <%=link_to @event.admin.email," "%></p>
  	</div>
</div>
</body>
</html>

app/views/home/Index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>EventBrite</title>
</head>
<body>
	<h1>Bienvenue dans EventBrite</h1>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!--       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script> -->

      <title>Eventbrite</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link href="vendor/assets/stylesheets/bootstrap.min.css" rel="stylesheet">

  <link href="vendor/assets/stylesheets/modern-business.css" rel="stylesheet">

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
          <%=link_to"EventBrite",root_path ,class:"navbar-brand" %>
          <div class="notice bg-success text-white "><%= notice%></div>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

            <li class="nav-item">
              <%=link_to"Home",root_path ,class:"nav-link" %>
            </li>

            <%if user_signed_in?%>
            <li class="nav-item">
              <%=link_to "Creer une évenement",new_event_path,class:"nav-link"%>
            </li>
            <%end%>

            <li class="nav-item">
              <a class="nav-link" href=" ">Contact</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Compte
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <%unless user_signed_in?%>
                  <%= link_to "Se connecter", new_user_session_path ,class:"dropdown-item" %>
                  <%= link_to "Creer un compte", new_user_registration_path ,class:"dropdown-item" %>
                  <div class="dropdown-divider"></div>
                <%else %>
                  <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete,class:"dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Profil",  users_controller_path(id:current_user.id),class:"dropdown-item" %>
                <%end%>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

</head>
  
  <body>
    <%= yield %>
  </body>




  <footer>
    <script src="vendor/assets/bootstrap.bundle.min.js"></script>
    <script type="vendor/assets/jquery.min.js"></script>
  </footer>
</html>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>EventBrite</title>
</head>
<body>
	<h1>Bienvenue dans EventBrite</h1>
	<ul>
	  <% if user_signed_in? %>
		    <li>
		      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
		    </li>

		    <li>
		      Voici ton email : <%= current_user.email %>
		    </li>

		    <li>
		      <%= link_to "Secret page", static_pages_secret_path %>
		    </li>

		    <li>
		      <%= link_to "Edit email / password", edit_user_registration_path %>
		    </li>

	  <% else %>
		    <li>    
		      <%= link_to "Sign in", new_user_session_path %>
		    </li>

		    <li>
		      <%= link_to "Sign up", new_user_registration_path %>
		    </li>

	  <% end %>
	</ul>

</body>
</html>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users_controller/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Profil user</title>
</head>
<body>
	<dir>

	</dir>

	<div class="row">

		<%if @user.avatar.attached?%>
			<div class="col-lg-6 ">
			<dir class="w-50 float-right" style="height: 100px"><%= image_tag @user.avatar, alt: 'avatar', class:"img-fluid rounded mb-4 " %></dir>
			</div> 
		<%else%>
		  <p>=== Il n'y a pas encore de photo de profile lié à cet utilisateur ! ===</p>
		<%end%>

      <div class="col-lg-6">
      	<h1>Vos informations</h1>
      	<p>Email : <%= current_user.email %></p>
      	<p>Nom : <%= current_user.last_name%></p>
      	<p>Prenom : <%= current_user.first_name%></p>
      	<p>Description : <%= current_user.description%> </p>
      	<p></p>
      	<p><%=link_to "Modifier mon profil",edit_user_registration_path%></p>
      	<h3>Changer de photo  ?</h3>
      	<%= form_tag users_controller_avatars_path(@user), multipart: true do %>
      	  <%= file_field_tag :avatar %>
      	  <%= submit_tag "mettre à jour" ,class:"btn btn-outline-dark" %>
      	<% end %>
      </div>
    </div>

</body>
</html>

app/views/users_controller/view.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Profil user</title>
</head>
<body>
	<h1>Vos informations</h1>
	<p>Email : <%= current_user.email %></p>
	<p>Nom : <%= current_user.last_name%></p>
	<p>Prenom : <%= current_user.first_name%></p>
	<p>Description : <%= current_user.description%> </p>
	<p></p>
	<p><%=link_to "Modifier mon profil",edit_user_registration_path%></p>
</body>
</html>